var GAME_LEVELS = [

  ["                                                                                    					        ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                               o                                                              o                 ",
   "                              xxx            c                                               xxx                ",
   "     c       o                        o                                              xxx                        ",
   "            xxx                      xxx                      o          o      xxx                             ",
   "                                                             xxx        xxx                         xxx         ",
   "    @                                             d                                                             ",
   "xxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxxxxxyyyyxxxxxxxxxxxxyyyy",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x                      		        ",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x          					        ",
   "                     x!!!!!x        x!!!x                  xxxxxxx     xxxxx                                    ",                                                 		
   "                     xxxxxxx        xxxxx                                                                       ",
   "                                                                                                                ",
   "                                                                                                                "],
 ["                                                                                    					        ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                        xxxx                                                                                    ",
   "                        x!!x                                                                                    ",
   "                        x!!x                                                                                    ",
   "                         v                                                                                      ",
   "                                            c                                                                   ",
   "                                   o                                                              o             ",
   "                         d        xxx                                                            xxx            ",
   "             o      xxxxxxxxxx           o     xxx                                        xxx                   ",
   "            xxx                         xxx                         o          o      xxx                       ",
   "        xxx                                           xxx          xxx        xxx                               ",
   "    @                                             d                                                             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxxxxxyyyyxxxxxxxxxxxxxxxx",
   "                                    x!!!x                  x!!!!!x     x!!!x                      		        ",
   "                                    x!!!x                  x!!!!!x     x!!!x          					        ",
   "                                    x!!!x                  xxxxxxx     xxxxx                                    ",                                                 		
   "                                    xxxxx                                                                       ",
   "                                                                                                                ",
   "                                                                                                                "],
   ["                                                                                    					        ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                        o                     d                                                                 ",
   "                 xxx xxxxxxx                                                                                    ",
   "           xxx       x!!!!!x          o                      o                                       o          ",
   "     xxx             x!!!!!x         xxx            o       xxx                                      xxx        ",
   "                     x!!!!!x              o        xxx                                    xxx                   ",
   "              xxx       v                xxx                       o          o      xxx                        ",
   "        xxx                       xxx                             xxx        xxx                         xxx    ",
   "    @                                              d                      d                                     ",
   "xxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxxxxxyyyyxxxxxxxxxxxxxxxx",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x                      		        ",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x          					        ",
   "                     x!!!!!x        x!!!x                  xxxxxxx     xxxxx                                    ",                                                 		
   "                     xxxxxxx        xxxxx                                                                       ",
   "                                                                                                                ",
   "                                                                                                                "],
  ["                                                                                    					        ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                       c                                                                                        ",
   "                                                   o                xxxxx                                       ",
   "                                                  xxx               x!!!x                                       ",
   "                                          d                         x!!!x                                       ",
   "                                     xxxxxxxxxxx         o            v                                         ",
   "                                                        xxx                          o                          ",
   "                               o                                  xxxxxxxxxx        xxx      o                  ",
   "                              xxx                 xxx                          o            xxx                 ",
   "              o       o                                                       xxx                               ",
   "            xxxxxxxxxxxxx                     xxx             o          o                                      ",
   "                                     xxx                     xxx        xxx                                     ",
   "    @          d                                   d                                                            ",
   "xxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxxxxxyyyyxxxxxxxxxxxxyyyy",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x                      		        ",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x          					        ",
   "                     x!!!!!x        x!!!x                  xxxxxxx     xxxxx                                    ",                                                 		
   "                     xxxxxxx        xxxxx                                                                       ",
   "                                                                                                                ",
   "                                                                                                                "],
 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
