var GAME_LEVELS = [

  ["                                                                                    					        ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                               o                                                             o                  ",
   "                              xxx                                                           xxx                 ",
   "             o                        o                                              xxx                        ",
   "            xxx                      xxx                      o          o      xxx                             ",
   "                                                             xxx        xxx                         xxx         ",
   "    @           d                                  d                                                            ",
   "xxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxxxxxyyyyxxxxxxxxxxxxyyyy",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x                      		        ",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x          					        ",
   "                     x!!!!!x        x!!!x                  xxxxxxx     xxxxx                                    ",                                                 		
   "                     xxxxxxx        xxxxx                                                                       ",
   "                                                                                                                ",
   "                                                                                                                "],
   ["                                                                                    					        ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                        xxxx                                                                                    ",
   "                        x!!x                                                                                    ",
   "                        x!!x                                                                                    ",
   "                                                                                                                ",
   "                                   o                                                             o              ",
   "                         d        xxx                                                           xxx             ",
   "             o      xxxxxxxxxx           o                                                xxx                   ",
   "            xxx                         xxx                         o          o      xxx                       ",
   "        xxx xxx                                       xxx          xxx        xxx                               ",
   "    @   xxx xxx                                  d                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxxxxxyyyyxxxxxxxxxxxxxxxx",
   "                                    x!!!x                  x!!!!!x     x!!!x                      		        ",
   "                                    x!!!x                  x!!!!!x     x!!!x          					        ",
   "                                    x!!!x                  xxxxxxx     xxxxx                                    ",                                                 		
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                "],
   ["                                                                                    					        ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                               o                                                             o                  ",
   "                              xxx                                                           xxx                 ",
   "             o                        o                                              xxx                        ",
   "            xxx                      xxx                      o          o      xxx                             ",
   "                                                             xxx        xxx                         xxx         ",
   "    @                                             d                                                             ",
   "xxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxxxxxyyyyxxxxxxxxxxxxyyyy",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x                      		        ",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x          					        ",
   "                     x!!!!!x        x!!!x                  xxxxxxx     xxxxx                                    ",                                                 		
   "                     xxxxxxx        xxxxx                                                                       ",
   "                                                                                                                ",
   "                                                                                                                "],
   ["                                                                                    					        ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                               o                                                             o                  ",
   "                              xxx                                                           xxx                 ",
   "             o                        o                                              xxx                        ",
   "            xxx                      xxx                      o          o      xxx                             ",
   "                                                             xxx        xxx                         xxx         ",
   "    @                                             d                                                             ",
   "xxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxxxxxxxxyyyyxxxxxxxxxxxxyyyy",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x                      		        ",
   "                     x!!!!!x        x!!!x                  x!!!!!x     x!!!x          					        ",
   "                     x!!!!!x        x!!!x                  xxxxxxx     xxxxx                                    ",                                                 		
   "                     xxxxxxx        xxxxx                                                                       ",
   "                                                                                                                ",
   "                                                                                                                "],
 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
